/**
 * Generates js/config.js from environment variables (used on Vercel deploy).
 * Required env: SUPABASE_URL, SUPABASE_ANON_KEY
 */
const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;
const outPath = path.join(__dirname, '..', 'js', 'config.js');

if (!url || !key) {
    console.error(
        'ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set in environment variables.'
    );
    process.exit(1);
}

const content = `/**
 * Auto-generated by scripts/generate-config.js — do not edit on production.
 */
window.PORTFOLIO_CONFIG = {
    supabaseUrl: '${url.replace(/'/g, "\\'")}',
    supabaseAnonKey: '${key.replace(/'/g, "\\'")}'
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Generated js/config.js successfully.');
